inputSet:
  name: Build_Sanjaypramod_nodejs_application_1737031056925-push-trigger-input-set
  identifier: Build_Sanjaypramod_nodejs_application_1737031056925pushtriggerinputset
  orgIdentifier: default
  projectIdentifier: default_project
  pipeline:
    identifier: Build_Sanjaypramod_nodejs_application_1737031056925
    properties:
      ci:
        codebase:
          build:
            type: branch
            spec:
              branch: <+trigger.branch>
